env:
  browser: true
  node: true
extends: 'eslint:recommended'
rules:
  curly:
    - error
    - all
  indent:
    - error
    - 2
    - { SwitchCase: 1 }
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
